### ISSUE TITLE
sorl-thumbnail is listed as a requirement but not included as a project dependency on setup.py

### ISSUE THREAD

**Issue by studiosi** [DigitalCampus/django-oppia#472]
The file requirements.txt contains this line

`sorl-thumbnail>=12.4,<13.0`

but then that dependency is not listed on the install_requires section on the setup.py file (all the others are). Is there are a reason for this? has been this dependency removed? PyCharm believes that the dependency is necessary but it is not installed through the setup process. If it is to be removed, I can do it, but I want to know what do you think first.

**Comment by alexlittle** [comment]
Actually it is needed for the latest version. I guess the reason for the inconsistency is that I usually use pip install -r requirements.txt for installing rather than the setup.py file.
We should do:
1. add to the setup.py and check that installing via setup.py and pip install -r requirements
2. update the docs as to the recommended install method
I used to publish django-oppia onto PyPi as a package, but haven;t been doing this for a while now - 2 basic reasons (1) it's a full website rather than just a library that could be reused and (2) people who install locally want to be able to adapt etc the code base, so better to clone & check out from github - so then use the setup or pip to get the requirements, rather than as a complete pypi package.

BTW - it's exactly these type of issues that are very helpful to get feedback on

**Comment by studiosi** [comment]
You can assign me this issue, it can be my first one 💃

**Comment by studiosi** [comment]
#473 Fixes the issue
