### ISSUE TITLE
Refactor django project structure

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/django-oppia#486]
Currently django-oppia is install as a sub-project of a django app - this make the initial setup more tricky for new devs as default project settings etc are at a higher level than the repository provides and so extra settings/params need to be added at the root django level.
refactoring this would also help with issues such as #477 and #468

**Comment by jjoseba** [comment]
Some annotattions I made about Django project structure after reading [Two scoops of Django](https://www.twoscoopspress.com/products/two-scoops-of-django-1-11) and I've found useful in other Django project:
  - use `requirements.txt` for project requirements (instead of `setup.py`)
  - a different app for each different task
  - create a module for settings, and keep the manage.py inside the repository
  - project-wide `templates` folder
  - project-wide `static` folder at root level
  - helpers in a root level module
  - REST API is best organized in a separate app
  - regarding settings, they can be separated in different files per subject, and also have a `settings_secret.py` file ignored in Git to have special settings like API keys, etc

**Comment by alexlittle** [comment]
Thanks Joseba, I think the setup.py approach is hangover from when I was publishing this to PyPi - but oppia isn't really the right 'type' of python code to publish there (it';s not a reusable/generic library that PyPi was relaly created for)
