### ISSUE TITLE
Refactor way quiz JSON object handles languages

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/django-oppia#487]
At the moment the quiz JSON looks like:
"description": {
       "en": "Pre-test"
   }

but a better approach might be:
"description": [{
            "language": "en",
            "i18n_description": "Pre-test"
        },
        {
            "language": "es",
            "i18n_description": "Pre-examen"
        }
    ]

This will need to be carefully thought through since it will affect all 3 Oppia components (moodle block, server and app) and decision will need to be made if we want to try to make all these backwards compatible too (my thought is that backwards compatibility might be too complicated).
In refactoring this it will make validation of the quiz JSON easier and is much more inline with good practice/structure

**Comment by studiosi** [comment]
The problem is that with the current structure "en" or whatever another language code is not a proper key, as it has a meaning other than finding the value. This issue makes that part of the quiz JSON impossible to validate with JSON schema unless we keep a list of the supported languages on the schema itself, which is not desirable.

**Comment by alexlittle** [comment]
transferred to OPPIA-46
