### ISSUE TITLE
Move cron and cronsummary tasks to be under the oppiamobile directory?

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/django-oppia#530]
Seems to make more sense to have them running from there with all the other server settings

**Comment by jjoseba** [comment]
I think the best approach for this would be to call this tasks using a management command, instead of calling directly the python file and having to load the Django path from the bash script. Right now, the cronsummary task is already exposed as `update_summaries` management command, so it can be called directly using `manage.py update_summaries`.
Then, the task would be to create a similar management command for the other task, and rewrite the bash scripts so they call them using the `manage.py` mechanism.

**Comment by alexlittle** [comment]
Thanks - sounds a good plan!
